### ISSUE TITLE
Demand curve type='line' creates supply instead. 

### ISSUE THREAD

**Issue by josh-r-foster** [R-CoderDotCom/econocharts#3]
To fix, replace at line 82 in the demand.R file with this 
`if(type == "line") {
      curve <- data.frame(x = c(xmax, 0.9),
                          y = c(0.9, ymax))
      m <- TRUE
    }`

Thanks for your work on this project -- I really like it!

**Comment by R-CoderDotCom** [comment]
Solved! Thank you for reporting this!
